#!/bin/sh
### BEGIN INIT INFO
# Provides:		WebTunnelAgent
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	macchina.io REMOTE Device Agent
### END INIT INFO
#
# Do not configure this file. Edit /etc/WebTunnelAgent.properties instead!
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/WebTunnelAgent
NAME=WebTunnelAgent
DESC="macchina.io REMOTE Device Agent"
CONFFILE=/etc/WebTunnelAgent.properties
PIDFILE=/var/run/WebTunnelAgent.pid

set -e

test -x "$DAEMON" || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON" -- --config=$CONFFILE --pidfile=$PIDFILE --daemon
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	sleep 1
	start-stop-daemon -S -p $PIDFILE \
	  -x "$DAEMON" -- --config=$CONFFILE --pidfile=$PIDFILE --daemon
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

